language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: EQbkwQr7CmpkFiuctoQKCeADiBr0stuGJNtEsDUkLSbYVbvHRYnRIB0IKR/U1Uz2y8NqIvRhuV97nzQH2036NvRbiIxA+4Y9Hg6Cn8uyyi1RMgaWHUPqdPBhPYcKGpf4TudnYqLin7qvRN0CCINA4UEUekH4HjhsDCXpCzZw5YKxWaTj1HtGUKhjDSw8ZrF9pxAIKybPKA8jJ0luxl0v/HnHf9zKTA4nnvDkL3if/Fn/9ajX5Ij6Q4fHnNmRiZYzYfz1B0BqWiQhJfh2qsho5a+viS3h/sTuXcq3ig83zoCG4Ybv7WOep1TwCwQFjeUCdvTsBYsBLA8pfzDoDDt9nPd0AXKLuyknq5kykVCXlCIrB23CiRRsvWN4173NTIZLH3kZiIZKAfZQC0ue3nYKNDqp+b1X1Cvz3J3yVKKECfBer+sQ9hzBhhGYm9LP7fHWHYpHRvAvpHTZRVKaXOLE8Qw2RKYpDVHYACLUQe6XyKzj5MEGkA1Wx0uwLl6LRcaeT3Zgc6WjGB8lV6sGp+7azIipqzQNQkAPtyzAlyEQB0RYiOSSWBVVo9HkQhIuTpdTM6THIrzGpEIhr9aOGYEosbTfGvyB+aabW0jDQg681fIneXZiLQIA2z2lwCQ0mRop9/qfJ63Z8To6uSsRa+mmPyU3Ci9vakD56LFjcsqooqA=
  app: aqueous-sierra-36847
  on:
    repo: gilmoreg/referendus
